# Generated by Django 5.0.1 on 2024-01-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
